services:
  fruggr-scanner:
    image: fruggr/scanner:latest
    # Our advice: always pull last available image
    pull_policy: always
    environment:
      - FRUGGR_API_KEY
      - FRUGGR_FUNIT_PATH
    volumes:
      - "./work:/tmp/fruggr"
      - $FRUGGR_FUNIT_PATH:$FRUGGR_FUNIT_PATH
